export type EmployerSummary = {
  id: string;
  name: string;
  county: string;
  contactName: string;
  contactEmail: string;
  arrangement: string;
  mouCode: string;
  mouStatus: string;
  paySchedule: string;
  purchaseOrderId: string;
  poNumber: string;
  poIssuedAt: string;
  poEffectiveEnd: string;
  poDocumentId: string | null;
  poDocumentName: string | null;
  originalFunding: number;
  amendmentFunding: number;
  currentFunding: number;
  committed: number;
  available: number;
  approved: number;
  paid: number;
  utilization: number;
};

export type PacketSummary = {
  id: string;
  employerId: string;
  employerName: string;
  purchaseOrderId: string;
  poNumber: string;
  internName: string | null;
  placement: string | null;
  supervisorName: string | null;
  supervisorEmail: string | null;
  county: string | null;
  fiscalYear: string;
  label: string;
  periodStart: string;
  periodEnd: string;
  status: string;
  priority: number;
  dueDate: string;
  invoiceNumber: string | null;
  invoiceAmount: number;
  wageAmount: number;
  businessAmount: number;
  confidence: number;
  receivedAt: string | null;
  approvedAt: string | null;
  paidAt: string | null;
  exceptions: PacketException[];
  documents: PacketDocument[];
  activities: ActivityHour[];
  claims: ReimbursementClaim[];
  history: AuditEvent[];
};

export type PacketException = {
  id: string;
  severity: number;
  title: string;
  detail: string;
  ownerRole: string;
  status: string;
  createdAt: string;
  resolvedAt: string | null;
  resolutionType: string | null;
  resolutionReason: string | null;
  resolvedBy: string | null;
};

export type PacketDocument = {
  id: string;
  kind: string;
  fileName: string;
  status: string;
  amount: number | null;
  uploadedAt: string;
  classificationConfidence: number;
  extractionProvider: string;
  hasOriginal: boolean;
  fieldEvidence: Array<{ id: string; name: string; value: unknown; confidence: number; source: string; status: string }>;
  extracted: Record<string, unknown>;
};

export type ActivityHour = { id: string; documentId: string | null; category: string; hours: number; source: string };
export type ReimbursementClaim = {
  id: string;
  documentId: string;
  type: string;
  description: string;
  businessPurpose: string;
  category: string;
  amountRequested: number;
  amountEligible: number | null;
  status: string;
  supportingDocumentId: string | null;
  supportingDocumentName: string | null;
  source: string;
  confidence: number;
  checks: EligibilityCheck[];
};
export type PublicPolicySource = { label: string; url: string };
export type EligibilityCheck = { id: string; authorityLevel: string; result: string; reason: string; confidence: number; reviewedAt: string | null; policyId: string | null; policyCode: string | null; policyVersion: string | null; sourceDocumentId: string | null; sourceDocumentName: string | null; publicSources: PublicPolicySource[] };
export type AuditEvent = { id: string; entityType: string; entityId: string; action: string; actor: string; occurredAt: string; before: unknown; after: unknown; reason: string | null };
export type MouSummary = { id: string; employerId: string; code: string; version: string; effectiveStart: string; effectiveEnd: string; status: string; allowedExpenses: string[]; limits: Record<string, number>; conditions: string[]; evidenceRequirements: string[]; documentId: string | null; documentName: string | null };
export type ProgramSettings = { id: string; name: string; hourlyRate: number; fiscalYearStart: string; fiscalYearEnd: string; invoiceDeadline: string; paymentDeadline: string; retentionYears: number; poWarningPercent: number; retentionAnchorDate: string | null; retentionPolicyConfirmed: boolean; retentionConfirmedAt: string | null; retentionConfirmedBy: string | null; retentionEligibleAt: string | null };
export type UnmatchedDocument = { id: string; employerId: string; employerName: string; kind: string; fileName: string; status: string; uploadedAt: string; confidence: number; provider: string; hasOriginal: boolean };
export type ReminderDraft = {
  id: string;
  employerId: string;
  employerName: string;
  contactEmail: string;
  recipientName: string | null;
  recipientRole: string;
  packetId: string | null;
  subject: string;
  body: string;
  status: string;
  createdAt: string;
  reviewedAt: string | null;
};
export type PoEvent = {
  id: string;
  purchaseOrderId: string;
  packetId: string | null;
  eventType: string;
  amount: number;
  reference: string;
  occurredAt: string;
  actor: string;
};
export type PolicyRecord = {
  id: string;
  level: string;
  title: string;
  code: string;
  status: string;
  summary: string;
  effectiveAt: string;
  effectiveEnd: string | null;
  version: string;
  sourceDocumentId: string | null;
  sourceDocumentName: string | null;
  publicSources: PublicPolicySource[];
  sourcesVerifiedAt: string | null;
};
export type DashboardData = {
  session: { email: string; name: string; role: "program_manager" | "fiscal_reviewer"; canManage: boolean };
  generatedAt: string;
  hourlyRate: number;
  fiscalYearEnd: string;
  paymentDeadline: string;
  employers: EmployerSummary[];
  packets: PacketSummary[];
  reminders: ReminderDraft[];
  poEvents: PoEvent[];
  policies: PolicyRecord[];
  settings: ProgramSettings;
  mous: MouSummary[];
  unmatchedDocuments: UnmatchedDocument[];
  retentionCandidates: Array<{ id: string; label: string; employerName: string; status: string; eligibleAt: string | null; documentCount: number }>;
};
